<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Wallpaper.jpg</name>
   <tag></tag>
   <elementGuidId>306b6056-6948-489a-b4e6-af47d6bbcae6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='uploaded-files']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#uploaded-files</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a7c18082-8442-499c-9260-773ba114fee9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uploaded-files</value>
      <webElementGuid>32e3c48f-69d4-4a19-9d7e-cb1730edf18a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>panel text-center</value>
      <webElementGuid>953760c0-5582-4e8d-ac27-7d96adfe1519</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
    Wallpaper.jpg
  </value>
      <webElementGuid>0f7552cc-44bd-4050-a95e-f0ee18b1b010</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uploaded-files&quot;)</value>
      <webElementGuid>aa3b44e6-4fa7-45d3-aad9-57325ec8a7c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='uploaded-files']</value>
      <webElementGuid>ae2acd9e-d8d9-43e4-91bc-de522da6321c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/div</value>
      <webElementGuid>ff6b5c4d-aa1f-4e4d-8462-91786422f9c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='File Uploaded!'])[1]/following::div[1]</value>
      <webElementGuid>7aa7dd10-69d1-4a0b-88a8-5fdc2dedf3d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Elemental Selenium'])[1]/preceding::div[1]</value>
      <webElementGuid>7ef1ba13-a54c-47cc-bfa7-73fd81f770a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Wallpaper.jpg']/parent::*</value>
      <webElementGuid>739e7dc9-18da-4d5d-983b-96f4142662bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div</value>
      <webElementGuid>24dac5a0-c152-4afe-bbfe-1edc412a654a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'uploaded-files' and (text() = '
    Wallpaper.jpg
  ' or . = '
    Wallpaper.jpg
  ')]</value>
      <webElementGuid>86b9a2f2-64dc-49d0-a7fe-b17401f75b1a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
